### PR TITLE
[review] Improve platform documentation

### PR DESCRIPTION
**Pull request by abought**
Refs: https://openscience.atlassian.net/browse/LEI-363

:warning: Must update this submodule commit after merging: https://github.com/CenterForOpenScience/exp-addons/pull/224

## Purpose
Kim has sent along some feedback on areas where documentation improvements would be helpful- we'll add various changes to address these items. 

This is not expected to contain any user facing changes (aside from perhaps readthedocs.org)

### General
- [x] Fix various typos
- [x] Build docs locally and make sure new pages appear (mixins, video_capture)
- [x] Final round of spell checking
- [ ] Verify that updated docs correctly propagate to readthedocs (must be done after PR is merged)

### Making custom frames:
- [x] Explanation of data vs. properties - how to access from within component.js and from template.hbs, what gets stored, what if you just want to have one of the properties also get stored (I could do parts of this & expand on places I think might be confusing, but am probably not the best person to start it)
- [x] Difference between functions defined as actions and functions just defined as part of the frame (and probably a warning not to just define functions globally?)
- [x] How to format the frame using an scss file (any general guidelines at this point for avoiding formatting all the frames, e.g. include .frame-name selectors throughout, and also a reminder to add to addon.scss. If the .scss file with a reminder to add to addon.scss could just happen during 'ember generate exp-frame frame-name', even better!
- [x] How/when/why to use MediaReload
- [x] How to use recording functionality within a frame

### Making custom randomizers
- [x] ❓ (FOLLOWUP depending on use case for randomizers) Explanation of 'options': needs to be clear that this is a list of frames to choose from, for randomizers that are going to do something with that list ("These should correspond with values from the frames object defined in the experiment structure" is surprisingly unclear or maybe I'm just dense - a quick example would help)
- [x] ❓ (FOLLOWUP) What arguments does the resolveFrame function take, and what does it do, exactly? Docs should point to lib/exp-player/addon/utils/parse-experiment.js if needed. I ended up just not using it...
  - Is a randomizer function actually supposed to have 3 arguments, or 4? Seems like this differs between pref-phys.js and the earlier shuffle.js, etc.

### CODE REVIEW

**Comment by abought** [comment]
There are certain questions involving legacy items that I will answer here on this ticket, pending discussion with @kimberscott about how best to document.

> What arguments does the resolveFrame function take, and what does it do, exactly? Docs should point to lib/exp-player/addon/utils/parse-experiment.js if needed. I ended up just not using it...

There are several [recognized kinds of frames](https://github.com/abought/exp-addons/blob/ece08446e342d9cc888123fa897fdeaed35e89ef/exp-player/addon/utils/parse-experiment.js#L77-L76) in experimenter. I would say the best information about how randomizers work is [here](https://github.com/abought/exp-addons/blob/ece08446e342d9cc888123fa897fdeaed35e89ef/exp-player/addon/utils/parse-experiment.js#L36-L36): modern randomizers like pref-phys take 4 arguments.

The reason you see some old examples that take 3 arguments is because the rules changed after `shuffle.js` was written- we wanted to be able to pass in past sessions (to support longitudinal studies). In looking at the git history and sample experiments, it appears that true randomizers never found an immediate use case on the platform, and the old code was not updated (in order to save time and prioritize for more immediate needs, like video recording).

There are also several [skipped unit tests](https://github.com/abought/exp-addons/blob/3be6e4389939fb6d12bf0790c99994c92e731595/exp-player/tests/unit/utils/parse-experiment-test.js#L57-L57) relating to this unused functionality- as you mention, modern experiments were not using it and therefore did not immediately miss the feature.

There are a range of possible solutions that depend heavily on intended use case. For example, the broken randomizers could be fixed, or removed to simplify the codebase. The final decision would determine how and whether to document this.

**Comment by kimberscott** [comment]
I'm fine with leaving shuffle.js and the other older randomizers be (maybe with some documentation in the frames that they are old examples and NOT for current use?), and implementing new ones as needed (perhaps generalizing after the next round of studies, based on what functionality we see needed). Updating/checking the randomizer template might still be helpful just for me, to make clear what the arguments & expected output are.

**Comment by abought** [comment]
> Updating/checking the randomizer template might still be helpful just for me, to make clear what the arguments & expected output are.

Good catch. Blueprint updated:
https://github.com/CenterForOpenScience/exp-addons/pull/224/commits/a9887138fb7370e5e837ec53459fa2ae48a7b53f#diff-9228368e242d6d6097f33b49a4404140R11

I've also gone in and deleted another blueprint (`addon-exp-frame`) that appeared to be legacy code, to avoid confusion with the very similar and more documented `exp-frame`.

**Comment by abought** [comment]
I've added some of the requested docs pages, and am passing to @kimberscott for initial feedback.

See also companion PR, which addresses some of the docstring and blueprint questions: https://github.com/CenterForOpenScience/exp-addons/pull/224

**Comment by abought** [comment]
Failing tests are due to new submodule commit not existing yet. Should be fixed naturally by merging https://github.com/CenterForOpenScience/exp-addons/pull/224

**Comment by kimberscott** [comment]
This looks terrific. Thanks so much for all your work here, including documenting what is actually fairly standard Ember functionality but is confusing to those of us using Ember for the first/only time for experimenter.

**Pull request merged**
