### PR TITLE
[rfr] Add support for bulk participant creation

### PR DESCRIPTION
**Pull request by abought**
Refs:
 https://openscience.atlassian.net/browse/LEI-305
(and maybe) https://openscience.atlassian.net/browse/LEI-312

⚠️ Depends on, and must be merged after updating submodule commit to reflect:
 https://github.com/CenterForOpenScience/exp-addons/pull/198

## Purpose
Add support for bulk participant creation. Limit to 100 records per attempt.

## Summary of changes
- Add bulk support for account creation: send 100 records in 1 request instead of 100
- Rely on JamDB bulk error reporting failure mechanism- instead of preemptively checking that a record exists already and guaranteeing 100 creations, let some fail and report how many succeeded. (may get a 200 status even if individual creation operations fail)

## Testing notes
- Create 1 record, check CSV
- Create 1 record with a specified field containing a password, and make sure extra fields are saved to CSV file
- Enter invalid batch size or study ID. Validation error text should not show initially, but should always show after the first time you click "create". Errors should display inline under the affected field.
- Batch size should be limited to 100, and validation should show errors when appropriate. Try typing in a batch size of 0, 1, 1.5, 100, and 101.
- Batch-create 2 records. Without reloading the page, create another batch of 2 participants. Each CSV file should cover only the entries created in that batch.
- Try to create 2 records, but edit the code for `createParticipants` to add a third record ID that already exists. The response payload should report 2 successful creations and one null placeholder in the data section (for the 3 records sent to the server), with 2 null placeholders and one "Document already exists" value in "errors" . 

## Known issues
- The UI appears to hang when creating a lot of records; this is not because of network requests. It seems that serialization is the slow step (because of bcrypt being done on the front end, which unfortunately is a requirement for now). Effectively, we made this operation take a long time for the user, *by design*.
  - We should try to make the UI more responsive in the future.

### CODE REVIEW

**Comment by samanehsan** [comment]
> Batch-create 2 records. Without reloading the page, create another batch of 2 participants. The second and final CSV file should have 4 entries (including the 2 from the first batch)

Why the change from the original behavior, where each batch was downloaded to a CSV file? I find it unintuitive to have to refresh the page each time I need the responses written to a new file.

**Comment by abought** [comment]
> Why the change from the original behavior, where each batch was downloaded to a CSV file? I find it unintuitive to have to refresh the page each time I need the responses written to a new file.

The refresh is a bit surprising and not an intentional change- was it like that before?

Basically, you could always click the button again to generate more records. You should get a CSV file every time you click create- the only intended difference is that now, your CSV file should reflect all the work you did on that visit to the page. (not just the most recent batch)

Under the hood, this is because bulk transactions are usually limited- you can't ask the server to do infinite work in a single request. In the OSF we limit it to 100 items per request, for example. The idea was that someone could respect that limit, but not have to track a bunch of extra CSV files and combine them on their own.

**Comment by samanehsan** [comment]
There is an issue with writing to the same CSV file when you change the extra fields. If I create records with the extra field "A", and then I delete that extra field and replace it with "B", the new CSV does not have the extra field "A" in it.

**Comment by abought** [comment]
> There is an issue with writing to the same CSV file when you change the extra fields. If I create records with the extra field "A", and then I delete that extra field and replace it with "B", the new CSV does not have the extra field "A" in it.

Hmm, that...  is probably a fair point for how CSV files are written. (it needs to get the list of fields from somewhere, and won't deal well if the rules change)

I'll simplify this down to only serializing the most recently created batch of records for now; we can revisit the added complexity required for improvements later.

**Comment by samanehsan** [comment]
@abought is it possible to change the participant ids in the downloaded csv from `isp.accounts.<participant_id>` to just the participant_id? After that, this is good to merge :octocat:

**Comment by abought** [comment]
> @abought is it possible to change the participant ids in the downloaded csv from isp.accounts.<participant_id> to just the participant_id? After that, this is good to merge :octocat:

I've pushed the changes- the csv writer now receives model instances again instead of pure JSON. As a result, headers are of the form `id`, `extra.studyId`, etc.

If it wouldn't trouble you too much, this could use an extra pair of hands poking one more time. I had to hack around ember a bit and create quasi-saved records, so I added some cleanup code (to make sure the broken account objects don't hang around the ember store later). It should clean up save errors from the ember inspector on save, and other accounts when you leave the page.

**Comment by samanehsan** [comment]
Looks good to me! I tested that an account with a participant ID that already exists cannot be created and gets cleared from the store. Also, remember to update the testing notes since each batch of participants is written to a separate CSV file.

**Pull request merged**
