### PR TITLE
Schema consolidation and cleanup (support)

### PR DESCRIPTION
**Pull request by abought**
Refs: https://openscience.atlassian.net/browse/LEI-136
Companion to: 
## Purpose

Remove unused fields from schemas, add documentation, and ensure that there is only one consistent source of truth for schema definitions.
## Summary of changes
- Remove fields
- Reconcile session schemas defined in two places (I briefly experimented with having node import from `const`, but no luck- suggestions welcome)
## Testing notes

There should be no user-facing changes; there is a strong assumption that all of these fields are totally unused.

### CODE REVIEW

**Comment by chrisseto** [comment]
Any reason we don't want to save the software version?

**Comment by abought** [comment]
> Any reason we don't want to save the software version?

Two basic reasons:
1. I haven't been able to get a clear answer what we mean by software version. Each frame, route, controller, and experiment can be versioned independently at present; there's no single definition for what this term means. We already save experiment version as a separate field.
2. I am trying to prune anything not actively used prior to launch- we've been saving empty strings in this field for the most part. We can add fields later, but I'd rather avoid littering records with fields we don't presently use.

**Comment by chrisseto** [comment]
Why not store the the commit hash? That is an absolute version that should be easy to automatically pull.

**Comment by abought** [comment]
> Why not store the the commit hash? That is an absolute version that should be easy to automatically pull.

Hmm. There is an [addon](https://github.com/rwjblue/ember-git-version) I've considered, as long as it doesn't cause deployment issues. I'd be happy to evaluate this a bit.

I'm willing to go that way, but we need an executive decision: either use the field, or remove it; no dummy data. @samchrisinger ?

**Pull request merged**
